### ISSUE TITLE
[windows] Some bugs

### ISSUE THREAD

**Issue by DreadDendy** [momentarylapse/tsunami#18]
Hi, I have tested Tsunami a bit and I have found some bugs.
1. Some icons are low-res and some widgets looks deformed
![icon_sizes](https://github.com/user-attachments/assets/745edd00-64d6-4dcc-a656-be44779b700b)
2. When app window is not full-screen there is a weird black frame around it
![win_gtk_weird](https://github.com/user-attachments/assets/e25b97c3-e68c-4128-b6ad-35cfce600787)
3. When I try to select another source (driver or channel) for audio recording then the application just freezes.
4. (may be not a bug due to current stage of development) In order to launch application I had to install Visual Studio Community 2022 because DAW requires some dlls for debug and development:
- msvcp140d.dll
- vcruntime140d.dll
- vcruntime140_1d.dll
- ucrtbased.dll

**Comment by momentarylapse** [comment]
Oh, that is highly valuable information. Thank you very much!

4. (missing dlls) was an easy fix. I reuploaded the zip file with those files included. Hope there are no others missing.
Yes, I admit, the Windows release is experimental. Will need to find a test system without Visual Studio installed.

1. Missing and low res icons are a known issue (also on MacOS). Somehow the gtk library comes with an incomplete icon theme. I'll try to find a way to include them and reupload.

1b. The stretched on/off switch is a bug in my code (the wrapper around gtk). Managed to fix in other places, but overlooked it here. Will fix soon.

1c. The overly large icons for the recording controls are ugly but intentional. Needed them on a touch screen. Will keep it for now, until a better design idea comes around. But I'm open for suggestions.

2. (black bars) Weird. Very likely a problem with gtk trying to render transparent shadows around window frames and failing to activate alpha blending. Might be an issue of gtk itself (if it also affects programs like GIMP). Or maybe my export is still missing some files. Will do some research.

3. (freeze) Reproduced. Yes, that's a clear bug. Should not take too long to fix.

**Comment by DreadDendy** [comment]
4. I uninstalled Visual Studio and checked again. Still not working without Visual Studio. This time error 0xc000007b on launch.
I think it is because those dlls are for debugging in Visual Studio. So it is basically debug build, not release build. Probably release build will not require these ones and will rely just on Visual C++ Redistributable.

**Comment by momentarylapse** [comment]
Ok, good to know. Yes, I had planned to make a "release" build, but Visual Studio recently fails during the (cmake) configuration process. Switching to "debug" still works.

I took down the Windows binaries for now. Will try again in a couple of days, but for now I'm too frustrated with Visual Studio.

The freeze (3.) turned out to be 2 bugs. One is clearly in my code and I managed to fix. The second seems to be strange behavior in the portaudio library (the default backend on Windows). Switching recording devices now works, but switching back fails to re-open the device. Still looking for a work-around.

Sorry and thanks a lot for your support!

**Comment by momentarylapse** [comment]
minor update: got my Visual Studio to produce "release" builds again. Also successfully tested on a clean (VM) install of Windows.

I'm optimistic to solve the icons issue in the following days. Then I'll upload again.

**Comment by momentarylapse** [comment]
I've uploaded another version (marked "EXPERIMENTAL" this time)

### what (hopefully) works:

* release build
* dlls included
* freeze fixed
* missing icons included
  * higher quality versions of some default icons
  * also replaced a few unicode symbols that were not shown due to incomplete font support (picture from MacOS)
<img width="764" alt="consistent-icons" src="https://github.com/user-attachments/assets/e2c248dc-4616-4d9a-acaf-d0338e0552cb">

### what is still incomplete:

* quite a few unicode symbols in text missing, especially midi track clefs
   * maybe simply installing extra fonts in the system might already fix this
<img width="168" alt="clef-missing" src="https://github.com/user-attachments/assets/5a390a9a-9d2e-4692-a179-6e39211fb3f3">

* dark theme would be nice
* a proper installer. Right now, it is awkward to start and the system gives security warnings

But these issues will have to wait till a later release.

Please, if you can spare a minute, could you download and try again?

**Comment by DreadDendy** [comment]
Hello. I have tried and I can confirm that these problems have been fixed.
- application works without Visual Studio
- it is possible to change audio devices
- icons fixed

**Comment by momentarylapse** [comment]
That is good to hear. Feel free to add more complaints. Thanks a lot!
