### ISSUE TITLE
Setup Travis CI for build AppImage (portable binary package for Linux)

### ISSUE THREAD

**Issue by ghost** [momentarylapse/tsunami#2]
Lets setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

0. [ ] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by Symbian9** [comment]
Are there any prebuilt binary for Linux already avaialble, @momentarylapse?

**Comment by momentarylapse** [comment]
Short answer: no.

Long answer: maybe in a month. I am currently finishing the port from gtk3 to gtk4. Besides that, the main problem is, that I am using a custom (and not very smart/portable) build system. Since I want to update that system for ticket #5 anyways, I can try making it more compatible with the CI system. Hard to predict how long that might take, since I am also dealing with some things in real life.

**Comment by Symbian9** [comment]
>  the main problem is, that I am using a custom (and not very smart/portable) build system

If so, providing AppImage is exactly the best solution for such project.

**Comment by luzpaz** [comment]
Would love there to be progress on this.

**Comment by momentarylapse** [comment]
just a quick "I'm working on it" update

First, I've decided against travis. It costs money. I've tried the free account but ran out, before I even got it working.

My current hope is for the github internal "workflow" system. I think I got the CI generally working, but still have to figure out how to build AppImages.

Since it is too frustrating to do the experiments in the CI, I've been playing around with the command line tools and tutorials. This is very draining. In the end, only managed to produce broken images so far (ironically even the official AppImage of the appimage-builder was broken).

I'll try again, but had enough for today.

**Comment by momentarylapse** [comment]
ok, I could not let it rest... I managed to create an AppImage:
https://github.com/momentarylapse/tsunami/releases/tag/v0.7.114

It works on my machine™. As far as I can tell, it uses files from within the image and not from my system. Although I'm not 100% sure. I'll try to find a setup for testing. But I'd be more than happy, if someone could also try this.
